{% set name = "hipfft" %}
{% set version = "1.0.13" %}
{% set rocm_version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/hipFFT/archive/refs/tags/rocm-{{ rocm_version }}.tar.gz
  sha256: c0a4bac5fa9a757a19a4995fa9571328b6ee0a71e93c66a880069794d65d284a

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - compiler-rt
    - clangdev
    - hip-devel
    - hipcc
    - lld
    - rocfft
    - rocm-cmake
    - rocm-device-libs
  run:
    - rocfft

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://rocm.docs.amd.com/projects/hipFFT
  summary: hipFFT library
  description: |
    hipFFT is an FFT marshalling library. Currently, hipFFT supports either rocFFT or cuFFT as the backend
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://rocm.docs.amd.com/projects/hipFFT
  dev_url: https://github.com/ROCm/hipFFT

extra:
  recipe-maintainers:
    - zklaus
